# Generated by Django 4.1.4 on 2023-01-09 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('OTG', models.CharField(max_length=40)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('group', models.IntegerField(default=1)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parserapp.street')),
            ],
        ),
    ]
