# Generated by Django 4.1.4 on 2023-02-24 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interruptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Start", models.DateTimeField(null=True, verbose_name="Start")),
                ("End", models.DateTimeField(null=True, verbose_name="End")),
                (
                    "Type",
                    models.CharField(
                        choices=[("Plan", "Plan"), ("Emergency", "Emergency")],
                        default="Plan",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interruption",
                "verbose_name_plural": "Interruptions",
            },
        ),
        migrations.CreateModel(
            name="Streets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=40, verbose_name="Name")),
                ("City", models.CharField(max_length=40, verbose_name="City")),
                ("OTG", models.CharField(max_length=40, verbose_name="OTG")),
                ("Region", models.CharField(max_length=40, verbose_name="Region")),
            ],
            options={
                "verbose_name": "Street",
                "verbose_name_plural": "Streets",
            },
        ),
        migrations.CreateModel(
            name="Buildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Address", models.CharField(max_length=4, verbose_name="Address")),
                (
                    "Group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Group",
                    ),
                ),
                (
                    "Longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "Latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "Interruption",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parserapp.interruptions",
                    ),
                ),
                (
                    "Street",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parserapp.streets",
                        verbose_name="Street",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
    ]
