# Generated by Django 4.1.4 on 2023-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parserapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildings",
            name="Group",
            field=models.CharField(
                blank=True,
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                max_length=10,
                null=True,
                verbose_name="Group",
            ),
        ),
    ]
