# Generated by Django 4.1.4 on 2023-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
