# Generated by Django 4.1.4 on 2023-01-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='group',
            field=models.IntegerField(blank=True),
        ),
    ]
