# Generated by Django 4.1.4 on 2023-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_alter_buildings_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='streets',
            name='Slug_city',
            field=models.SlugField(allow_unicode=True, default=None, verbose_name='Slug city'),
        ),
        migrations.AddField(
            model_name='streets',
            name='Slug_street',
            field=models.SlugField(allow_unicode=True, default=None, verbose_name='Slug street'),
        ),
    ]
