# Generated by Django 4.1.4 on 2023-01-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0004_alter_building_address_alter_building_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Address', models.CharField(max_length=4, verbose_name='Address')),
                (
                    'Group',
                    models.CharField(
                        blank=True,
                        choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')],
                        max_length=1,
                        verbose_name='Group',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Interruptions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Start', models.DateTimeField(null=True, verbose_name='Start')),
                ('End', models.DateTimeField(null=True, verbose_name='End')),
                (
                    'Type',
                    models.CharField(
                        choices=[('0', 'Plan'), ('1', 'Emergency')],
                        default=('0', 'Plan'),
                        max_length=1,
                        verbose_name='Type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Interruption',
                'verbose_name_plural': 'Interruptions',
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Name', models.CharField(max_length=40, verbose_name='Name')),
                ('City', models.CharField(max_length=40, verbose_name='City')),
                ('OTG', models.CharField(max_length=40, verbose_name='OTG')),
                ('Region', models.CharField(max_length=40, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
            },
        ),
        migrations.RemoveField(
            model_name='street',
            name='region',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.AddField(
            model_name='buildings',
            name='Interruption',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='parserapp.interruptions',
            ),
        ),
        migrations.AddField(
            model_name='buildings',
            name='Street',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='parserapp.streets',
                verbose_name='Street',
            ),
        ),
    ]
