# Generated by Django 4.1.4 on 2023-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0004_streets_slug_city_streets_slug_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='Slug_city',
            field=models.SlugField(allow_unicode=True, null=True, verbose_name='Slug city'),
        ),
        migrations.AlterField(
            model_name='streets',
            name='Slug_street',
            field=models.SlugField(allow_unicode=True, null=True, verbose_name='Slug street'),
        ),
    ]
