# Generated by Django 4.1.4 on 2023-05-31 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parserapp', '0002_first_user'),
        ('parserapp', '0006_alter_streets_slug_city_alter_streets_slug_street'),
    ]

    operations = []
