FROM python:3.11.1

WORKDIR /blackout

COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt
COPY . .
RUN python manage.py migrate

EXPOSE 8000

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["gunicorn", "-b", "0.0.0.0:8000", "--worker-class", "gevent", "blackout.wsgi"]
